
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 2;
  public static final int TKLOG = 7;
  public static final int MENOS = 13;
  public static final int PUNTO = 4;
  public static final int UMENOS = 14;
  public static final int MULT = 8;
  public static final int NUMEROS = 3;
  public static final int EOF = 0;
  public static final int MAS = 12;
  public static final int PAR2 = 11;
  public static final int PAR1 = 10;
  public static final int TKCONSOLE = 6;
  public static final int DIV = 9;
  public static final int FINCADENA = 5;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "NUMEROS",
  "PUNTO",
  "FINCADENA",
  "TKCONSOLE",
  "TKLOG",
  "MULT",
  "DIV",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS"
  };
}

